# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Aug 27 01:46:30 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 510))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ct_layout_0 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.ct_layout_0.setContentsMargins(0, 0, 0, 0)
        self.ct_layout_0.setObjectName("ct_layout_0")
        self.ct_groupbox_src = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.ct_groupbox_src.setObjectName("ct_groupbox_src")
        self.ct_layout_dst_1 = QtWidgets.QHBoxLayout(self.ct_groupbox_src)
        self.ct_layout_dst_1.setSpacing(2)
        self.ct_layout_dst_1.setContentsMargins(6, 2, 6, 6)
        self.ct_layout_dst_1.setObjectName("ct_layout_dst_1")
        self.ct_tree_src = QtWidgets.QTreeWidget(self.ct_groupbox_src)
        self.ct_tree_src.setMinimumSize(QtCore.QSize(0, 200))
        self.ct_tree_src.setStyleSheet("font-family: monospace;")
        self.ct_tree_src.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ct_tree_src.setObjectName("ct_tree_src")
        self.ct_tree_src.header().setVisible(False)
        self.ct_layout_dst_1.addWidget(self.ct_tree_src)
        self.ct_layout_dst_2 = QtWidgets.QVBoxLayout()
        self.ct_layout_dst_2.setSpacing(2)
        self.ct_layout_dst_2.setObjectName("ct_layout_dst_2")
        self.ct_append_src = QtWidgets.QPushButton(self.ct_groupbox_src)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_append_src.sizePolicy().hasHeightForWidth())
        self.ct_append_src.setSizePolicy(sizePolicy)
        self.ct_append_src.setObjectName("ct_append_src")
        self.ct_layout_dst_2.addWidget(self.ct_append_src)
        self.ct_remove_src = QtWidgets.QPushButton(self.ct_groupbox_src)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_remove_src.sizePolicy().hasHeightForWidth())
        self.ct_remove_src.setSizePolicy(sizePolicy)
        self.ct_remove_src.setObjectName("ct_remove_src")
        self.ct_layout_dst_2.addWidget(self.ct_remove_src)
        self.ct_clear_src = QtWidgets.QPushButton(self.ct_groupbox_src)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_clear_src.sizePolicy().hasHeightForWidth())
        self.ct_clear_src.setSizePolicy(sizePolicy)
        self.ct_clear_src.setObjectName("ct_clear_src")
        self.ct_layout_dst_2.addWidget(self.ct_clear_src)
        self.ct_clean_src = QtWidgets.QPushButton(self.ct_groupbox_src)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_clean_src.sizePolicy().hasHeightForWidth())
        self.ct_clean_src.setSizePolicy(sizePolicy)
        self.ct_clean_src.setObjectName("ct_clean_src")
        self.ct_layout_dst_2.addWidget(self.ct_clean_src)
        self.ct_layout_dst_1.addLayout(self.ct_layout_dst_2)
        self.ct_layout_0.addWidget(self.ct_groupbox_src)
        self.ct_groupbox_dst = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.ct_groupbox_dst.setObjectName("ct_groupbox_dst")
        self.ct_layout_src_1 = QtWidgets.QHBoxLayout(self.ct_groupbox_dst)
        self.ct_layout_src_1.setSpacing(2)
        self.ct_layout_src_1.setContentsMargins(6, 2, 6, 6)
        self.ct_layout_src_1.setObjectName("ct_layout_src_1")
        self.ct_tree_dst = QtWidgets.QTreeWidget(self.ct_groupbox_dst)
        self.ct_tree_dst.setMinimumSize(QtCore.QSize(0, 200))
        self.ct_tree_dst.setStyleSheet("font-family: monospace;")
        self.ct_tree_dst.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ct_tree_dst.setObjectName("ct_tree_dst")
        self.ct_tree_dst.header().setVisible(False)
        self.ct_layout_src_1.addWidget(self.ct_tree_dst)
        self.ct_layout_src_2 = QtWidgets.QVBoxLayout()
        self.ct_layout_src_2.setSpacing(2)
        self.ct_layout_src_2.setObjectName("ct_layout_src_2")
        self.ct_append_dst = QtWidgets.QPushButton(self.ct_groupbox_dst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_append_dst.sizePolicy().hasHeightForWidth())
        self.ct_append_dst.setSizePolicy(sizePolicy)
        self.ct_append_dst.setObjectName("ct_append_dst")
        self.ct_layout_src_2.addWidget(self.ct_append_dst)
        self.ct_remove_dst = QtWidgets.QPushButton(self.ct_groupbox_dst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_remove_dst.sizePolicy().hasHeightForWidth())
        self.ct_remove_dst.setSizePolicy(sizePolicy)
        self.ct_remove_dst.setObjectName("ct_remove_dst")
        self.ct_layout_src_2.addWidget(self.ct_remove_dst)
        self.ct_clear_dst = QtWidgets.QPushButton(self.ct_groupbox_dst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_clear_dst.sizePolicy().hasHeightForWidth())
        self.ct_clear_dst.setSizePolicy(sizePolicy)
        self.ct_clear_dst.setObjectName("ct_clear_dst")
        self.ct_layout_src_2.addWidget(self.ct_clear_dst)
        self.ct_clean_dst = QtWidgets.QPushButton(self.ct_groupbox_dst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_clean_dst.sizePolicy().hasHeightForWidth())
        self.ct_clean_dst.setSizePolicy(sizePolicy)
        self.ct_clean_dst.setObjectName("ct_clean_dst")
        self.ct_layout_src_2.addWidget(self.ct_clean_dst)
        self.ct_layout_src_1.addLayout(self.ct_layout_src_2)
        self.ct_layout_0.addWidget(self.ct_groupbox_dst)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ct_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ct_start.sizePolicy().hasHeightForWidth())
        self.ct_start.setSizePolicy(sizePolicy)
        self.ct_start.setObjectName("ct_start")
        self.horizontalLayout.addWidget(self.ct_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ct_start.clicked.connect(MainWindow.ct_start_clicked)
        self.ct_tree_src.itemCollapsed['QTreeWidgetItem*'].connect(MainWindow.ct_tree_itemcollapsed)
        self.ct_append_src.clicked.connect(MainWindow.ct_append_src_clicked)
        self.ct_remove_src.clicked.connect(MainWindow.ct_remove_clicked)
        self.ct_clean_src.clicked.connect(MainWindow.ct_clean_src_clicked)
        self.ct_append_dst.clicked.connect(MainWindow.ct_append_dst_clicked)
        self.ct_remove_dst.clicked.connect(MainWindow.ct_remove_clicked)
        self.ct_clean_dst.clicked.connect(MainWindow.ct_clean_dst_clicked)
        self.ct_tree_src.itemExpanded['QTreeWidgetItem*'].connect(MainWindow.ct_tree_itemexpanded)
        self.ct_clear_src.clicked.connect(MainWindow.ct_clear_clicked)
        self.ct_clear_dst.clicked.connect(MainWindow.ct_clear_clicked)
        self.ct_tree_dst.itemCollapsed['QTreeWidgetItem*'].connect(MainWindow.ct_tree_itemcollapsed)
        self.ct_tree_dst.itemExpanded['QTreeWidgetItem*'].connect(MainWindow.ct_tree_itemexpanded)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.ct_tree_src)
        MainWindow.setTabOrder(self.ct_tree_src, self.ct_append_src)
        MainWindow.setTabOrder(self.ct_append_src, self.ct_remove_src)
        MainWindow.setTabOrder(self.ct_remove_src, self.ct_clean_src)
        MainWindow.setTabOrder(self.ct_clean_src, self.ct_tree_dst)
        MainWindow.setTabOrder(self.ct_tree_dst, self.ct_append_dst)
        MainWindow.setTabOrder(self.ct_append_dst, self.ct_remove_dst)
        MainWindow.setTabOrder(self.ct_remove_dst, self.ct_clean_dst)
        MainWindow.setTabOrder(self.ct_clean_dst, self.ct_start)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SubtitleResyncHelper"))
        self.ct_groupbox_src.setTitle(_translate("MainWindow", "原始文件"))
        self.ct_tree_src.headerItem().setText(0, _translate("MainWindow", "name"))
        self.ct_tree_src.headerItem().setText(1, _translate("MainWindow", "dir"))
        self.ct_append_src.setText(_translate("MainWindow", "添加"))
        self.ct_remove_src.setText(_translate("MainWindow", "移除"))
        self.ct_clear_src.setText(_translate("MainWindow", "清空"))
        self.ct_clean_src.setText(_translate("MainWindow", "清理"))
        self.ct_groupbox_dst.setTitle(_translate("MainWindow", "目标文件"))
        self.ct_tree_dst.headerItem().setText(0, _translate("MainWindow", "name"))
        self.ct_tree_dst.headerItem().setText(1, _translate("MainWindow", "dir"))
        self.ct_append_dst.setText(_translate("MainWindow", "添加"))
        self.ct_remove_dst.setText(_translate("MainWindow", "移除"))
        self.ct_clear_dst.setText(_translate("MainWindow", "清空"))
        self.ct_clean_dst.setText(_translate("MainWindow", "清理"))
        self.ct_start.setText(_translate("MainWindow", "开始"))

